Repository paritytech/cargo-contract, pull requests merged in 2021-08, with the labels that each got.

#322 CI: force cache pre-population
  scripts/pre_cache.sh
Labels: bug, ci

#323 Mention the contracts Docker image in the project README
  README.md
Labels: documentation

#325 Use new dependency resolver for template contract
  CHANGELOG.md
  templates/new/_Cargo.toml
Labels: enhancement

#324 Add option for JSON formatted output
  CHANGELOG.md
  src/cmd/build.rs
  src/cmd/metadata.rs
  src/main.rs
Labels: enhancement
