Repository paritytech/cargo-contract, pull requests merged in 2021-07, with the labels that each got.

#302 Add `--keep-symbols` flag
  Cargo.lock
  Cargo.toml
  src/cmd/build.rs
  src/cmd/metadata.rs
Labels: enhancement

#306 Apply clippy to all code
  .gitlab-ci.yml
  src/cmd/build.rs
  src/cmd/deploy.rs
  src/cmd/instantiate.rs
  src/cmd/metadata.rs
  src/workspace/manifest.rs
Labels: ci

#303 Fix tests on macOS
  src/util.rs
Labels: bug

#305 Change default optimizations pass to focus on code size
  CHANGELOG.md
  src/cmd/build.rs
  src/main.rs
Labels: enhancement

#298 Implement `BuildMode`
  .rustfmt.toml
  CHANGELOG.md
  src/cmd/build.rs
  src/cmd/metadata.rs
  src/main.rs
Labels: blocked
